/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fameLadySquadSol from "./FameLadySquad.sol";
export type { fameLadySquadSol };
import type * as namedLadyRendererSol from "./NamedLadyRenderer.sol";
export type { namedLadyRendererSol };
import type * as testRendererSol from "./TestRenderer.sol";
export type { testRendererSol };
export type { BulkMinter } from "./BulkMinter";
export type { FameLadySociety } from "./FameLadySociety";
export type { Fameus } from "./Fameus";
export type { IERC4906 } from "./IERC4906";
export type { ITokenURIGenerator } from "./ITokenURIGenerator";
export type { TestNFT } from "./TestNFT";
export type { WrappedNFT } from "./WrappedNFT";
