/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IERC4906, IERC4906Interface } from "../../contracts/IERC4906";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_fromTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_toTokenId",
        type: "uint256",
      },
    ],
    name: "BatchMetadataUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "MetadataUpdate",
    type: "event",
  },
] as const;

export class IERC4906__factory {
  static readonly abi = _abi;
  static createInterface(): IERC4906Interface {
    return new Interface(_abi) as IERC4906Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC4906 {
    return new Contract(address, _abi, runner) as unknown as IERC4906;
  }
}
