/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenURIGenerator,
  ITokenURIGeneratorInterface,
} from "../../contracts/ITokenURIGenerator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenURIGenerator__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenURIGeneratorInterface {
    return new Interface(_abi) as ITokenURIGeneratorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenURIGenerator {
    return new Contract(address, _abi, runner) as unknown as ITokenURIGenerator;
  }
}
