/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  EmitableMetadtata,
  EmitableMetadtataInterface,
} from "../../../contracts/TestRenderer.sol/EmitableMetadtata";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_fromTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_toTokenId",
        type: "uint256",
      },
    ],
    name: "BatchMetadataUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "MetadataUpdate",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "emitMetadataUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class EmitableMetadtata__factory {
  static readonly abi = _abi;
  static createInterface(): EmitableMetadtataInterface {
    return new Interface(_abi) as EmitableMetadtataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EmitableMetadtata {
    return new Contract(address, _abi, runner) as unknown as EmitableMetadtata;
  }
}
