/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenMetadataEmit,
  ITokenMetadataEmitInterface,
} from "../../../contracts/NamedLadyRenderer.sol/ITokenMetadataEmit";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "emitMetadataUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isApprovedForAll",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenMetadataEmit__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenMetadataEmitInterface {
    return new Interface(_abi) as ITokenMetadataEmitInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenMetadataEmit {
    return new Contract(address, _abi, runner) as unknown as ITokenMetadataEmit;
  }
}
